name: opencv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argon2-cffi=20.1.0=py38h25fe258_2
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.12.8=h06a4308_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.4=py38ha312104_0
  - cpuonly=1.0=0
  - cycler=0.10.0=py_2
  - cython=0.29.21=py38h950e882_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.2.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=nompi_h3c11f04_100
  - icu=64.2=he1b5a44_1
  - importlib-metadata=3.3.0=py38h578d9bd_2
  - importlib_metadata=3.3.0=hd8ed1ab_2
  - intel-openmp=2020.1=217
  - ipykernel=5.3.0=py38h5ca1d4c_0
  - ipympl=0.5.8=pyh9f0ad1d_0
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.17.1=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38_0
  - kiwisolver=1.2.0=py38hbf85e49_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.34=h53a641e_5
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=16_openblas
  - liblapacke=3.8.0=16_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.9=h5ec1e0e_0
  - libopencv=4.3.0=py38_1
  - libpng=1.6.37=hed695b0_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_1
  - markupsafe=1.1.1=py38h8df0ef7_2
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38h2af1d28_0
  - mistune=0.8.4=py38h25fe258_1002
  - mkl=2020.1=217
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.8=py_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=py38hfd86e86_0
  - nodejs=10.13.0=he6710b0_0
  - notebook=6.1.5=py38h578d9bd_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.5=py38h8854b6b_0
  - olefile=0.46=py_0
  - opencv=4.3.0=py38_1
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3deb0d_0
  - pandoc=2.11.3=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.5=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py38_0
  - py-opencv=4.3.0=py38h23f93f0_1
  - pycocotools=2.0.1=py38h1e0a361_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38ha8c2ead_3
  - pyrsistent=0.17.3=py38h25fe258_1
  - python=3.8.3=cpython_he5300dc_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_cpu_0
  - pyzmq=19.0.1=py38he6710b0_1
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - send2trash=1.5.0=py_0
  - setuptools=47.3.1=py38h32f6830_0
  - six=1.15.0=py_0
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.9.1=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.5.0=py38_cpu
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=4.3.3=py38_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - zeromq=4.3.2=he6710b0_2
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
